# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65552b3166aa518b0a0d9e93ddd602fed76a202028d92fe21ae21b754837b757c6dcdba5906ef236ac10e180813dc9dde431f3d4611edb098472178a478c5d99

test:
  secret_key_base: ca5589ce41644270c6e9cce1f3a6eb69e58839bc543f3bd83f1faa5f0b048caf96bf350b8e40b81cffb1f84411c52d8ceb71a947cc53d1fddfa1b5eb0866f77c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
